### ISSUE TITLE
Trying to compile for armhf won't work.

### ISSUE THREAD

**Issue by nextime** [wor/goanysync#16]
running "make":

 unhandled CPU exception 0x2 - aborting
R00=00000004 R01=f6fff4f8 R02=00000000 R03=00000008
R04=0007be19 R05=00000000 R06=00000000 R07=000000ae
R08=00000000 R09=00000000 R10=00448000 R11=00000000
R12=00000000 R13=f6fff4f8 R14=0007bdcc R15=0007be1a
PSR=00000030 ---- T usr32

**Comment by nextime** [comment]
The first was on a qemu emulated chroot.
This is on the real hardware ( a raspberry pi with raspbian ):

   dh_auto_build
make[2]: Entering directory `/root/goanysync-master/goanysync-1.10b'
GOPATH=$(readlink -f .):${GOPATH} go build  -o goanysync goanysync/goanysync
SIGILL: illegal instruction
PC=0x7d394

math.init·1()
    /usr/lib/go/src/pkg/math/pow10.go:34 +0x28
math.init()
    /usr/lib/go/src/pkg/math/unsafe.go:21 +0x70
strconv.init()
    /usr/lib/go/src/pkg/strconv/quote.go:441 +0x70
go/parser.init()
    /usr/lib/go/src/pkg/go/parser/parser.go:2349 +0x78
main.init()
    /usr/lib/go/src/cmd/go/vet.go:37 +0x78

goroutine 2 [runnable]:
created by runtime.main
    /build/golang-FunV5r/golang-1.0.2/src/pkg/runtime/proc.c:221

trap    0x6
error   0x0
oldmask 0x0
r0      0x86c5b0
r1      0x0
r2      0x0
r3      0x0
r4      0x0
r5      0x0
r6      0x0
r7      0x0
r8      0x0
r9      0x45e29c
r10     0x10953000
fp      0x86c172
ip      0xcafebabe
sp      0x40134e4c
lr      0x7d928
pc      0x7d394
cpsr    0x20000010
fault   0x0
make[2]: **\* [goanysync] Error 2
make[2]: Leaving directory `/root/goanysync-master/goanysync-1.10b'
dh_auto_build: make -j1 returned exit code 2
make[1]: *** [build] Error 2
make[1]: Leaving directory`/root/goanysync-master/goanysync-1.10b'
dpkg-buildpackage: error: debian/rules build gave error exit status 2
make: **\* [goanysync-1.10b-1_i386.deb] Error 2
